version: '3.3'
services:
  iprwc-database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: iprwc-database
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: .env

  iprwc-api:
    build: .
    container_name: iprwc-api
    depends_on:
      - iprwc-database
    restart: unless-stopped
    ports:
      - "5000:5000"

networks:
  default:
    external:
      name: main
