version: '3.3'
services:
  iprwc-database:
    image: mariadb
    container_name: iprwc-database
    restart: unless-stopped
    ports:
      - "3306:3306"

  iprwc-api:
    build: .
    container_name: iprwc-api
    restart: unless-stopped
    ports:
      - "5000:5000"

networks:
  default:
    external:
      name: main
